export const STADIUMS = [
  {
    name: "METROPOLITANO",
    subtitle: "Celebración por banda",
    skyTop: "#152E4D",
    skyBottom: "#2E5677",
    standA: "#CB3234",
    standB: "#253166",
    accent: "#8E2022",
    obstacles: [
      { type: "player", name: "Rival", w: 52, h: 35, color: "#FFFFFF", detail: "#1E88E5", pts: 12, avoidBy: "lane" },
      { type: "mole", name: "Topo", w: 40, h: 32, color: "#7A5830", detail: "#5C4325", pts: 25, avoidBy: "lane" },
      { type: "cone", name: "Cono", w: 24, h: 42, color: "#FF6D00", detail: "#FFFFFF", pts: 15, avoidBy: "lane" },
      { type: "camera", name: "Cámara", w: 46, h: 36, color: "#3A3A3A", detail: "#5C6BC0", pts: 18, avoidBy: "lane" },
      { type: "sprinkler", name: "Aspersor", w: 30, h: 22, color: "#90A4AE", detail: "#64B5F6", pts: 14, avoidBy: "lane" },
    ],
  },
  {
    name: "OLD TRAFFORD",
    subtitle: "Ahora sí te tiran cosas",
    skyTop: "#272727",
    skyBottom: "#4B4B4B",
    standA: "#DA291C",
    standB: "#F7E85D",
    accent: "#AA1B13",
    obstacles: [
      { type: "bottle", name: "Botella", w: 18, h: 30, color: "#42A5F5", detail: "#BBDEFB", pts: 15, avoidBy: "duck" },
      { type: "lighter", name: "Mechero", w: 14, h: 22, color: "#FF9800", detail: "#FFD54F", pts: 12, avoidBy: "duck" },
      { type: "scarf", name: "Bufanda", w: 56, h: 16, color: "#DA291C", detail: "#F7E85D", pts: 20, avoidBy: "duck" },
      { type: "coin", name: "Moneda", w: 18, h: 18, color: "#FFD700", detail: "#FFF176", pts: 24, avoidBy: "duck" },
      { type: "beer", name: "Vaso", w: 24, h: 30, color: "#FDD835", detail: "#FFFFFF", pts: 16, avoidBy: "duck" },
    ],
  },
  {
    name: "BERNABÉU",
    subtitle: "Que no te birlen nada",
    skyTop: "#17172D",
    skyBottom: "#33335F",
    standA: "#FFFFFF",
    standB: "#6D4BC3",
    accent: "#D4AF37",
    obstacles: [
      { type: "pickpocket", name: "Carterista", w: 42, h: 46, color: "#252525", detail: "#D7B088", pts: 30, avoidBy: "lane" },
      { type: "wallet", name: "Cartera", w: 28, h: 20, color: "#8D6E63", detail: "#A1887F", pts: 16, avoidBy: "lane" },
      { type: "watch", name: "Reloj", w: 22, h: 22, color: "#FFD54F", detail: "#FFF8E1", pts: 22, avoidBy: "lane" },
      { type: "camera", name: "Cámara VAR", w: 46, h: 36, color: "#212121", detail: "#7C4DFF", pts: 18, avoidBy: "lane" },
      { type: "cone", name: "Cono VIP", w: 24, h: 42, color: "#D4AF37", detail: "#FFFFFF", pts: 14, avoidBy: "lane" },
    ],
  },
];
